# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
v1 = np.zeros(10)

3. Create a vector with values ranging from 10 to 49

In [3]:
v2 = np.arange(10,49)

4. Find the shape of previous array in question 3

In [4]:
print(v2.shape)

(39,)


5. Print the type of the previous array in question 3

In [5]:
print(type(v2))

<class 'numpy.ndarray'>


6. Print the numpy version and the configuration


In [6]:
print(np.__version__)
print(np.show_config())

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Talha ALi/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Talha ALi/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Talha ALi/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\w

7. Print the dimension of the array in question 3


In [7]:
print(v2.shape)

(39,)


8. Create a boolean array with all the True values

In [8]:
v3 = np.ones(10,dtype=bool)

9. Create a two dimensional array




In [9]:
v4 = [[1,2,3],[4,5,6]]

10. Create a three dimensional array



v5 = [[[1],[2],[3]],[[4],[5]]]

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [10]:
v5 = [1,2,3,4,5]
print(v5)
rev = v5[::-1]
print(rev)

[1, 2, 3, 4, 5]
[5, 4, 3, 2, 1]


12. Create a null vector of size 10 but the fifth value which is 1 

v6 = np.zeros(10)
v6[5] = 1
print(v6)

13. Create a 3x3 identity matrix

In [11]:
v7 = np.ones((3,3))

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [12]:
arr = np.array([1,2,3,4,5])
arr = arr.astype('float64')
print(arr)

[1. 2. 3. 4. 5.]


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [13]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
mult = arr1*arr2
print(mult)

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

17. Extract all odd numbers from arr with values(0-9)

In [14]:
arr = np.arange(10)
arr[arr%2 == 1]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [15]:
arr[arr%2 == 1] = -1

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [16]:
arr = np.arange(10)
arr[5:9] = 12

20. Create a 2d array with 1 on the border and 0 inside

In [17]:
arr = np.ones((5,5))
arr[1:-1,1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [18]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[arr2d == 5] = 12
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [19]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0] = 64
print(arr3d)

[[[64 64 64]
  [64 64 64]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [20]:
arr = np.arange(10)
arr = arr.reshape(2,5)
Slice = arr[0]
print(Slice)

[0 1 2 3 4]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [21]:
arr = np.arange(10)
arr = arr.reshape(2,5)
Slice = arr[1,1]
print(Slice)

6


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

26. Create a 10x10 array with random values and find the minimum and maximum values

In [25]:
arr = np.random.rand(10,10)
print(np.min(arr))
print(np.max(arr))

0.021777331914915266
0.9962865824282734


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [31]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])

print(np.intersect1d(a,b))

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [35]:
loc = np.where(a == b)
print(loc)

(array([1, 3, 5, 7], dtype=int64),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [37]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
loc = np.where(names != 'Will')
print(data[loc])

[[-1.36126248  0.03612378 -1.9939766   0.5643456 ]
 [ 0.63395018  0.26785006 -1.85969195 -1.40639148]
 [ 0.53017267  0.97129095  0.30470653 -0.20643074]
 [-1.46118906 -0.62239148  0.42407707 -1.27169789]
 [-0.89429405 -0.1068132   0.28788854 -0.0196074 ]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [45]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
loc = np.where(names != 'Will')
loc2 = np.where(names != 'Joe')
loc3 = np.intersect1d(loc,loc2)
print(data[loc3])

[[-0.0274372  -1.21687845 -1.29695902  0.60614708]
 [-0.36546588  0.93811651 -0.41518048 -0.54333088]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [52]:
arr = np.random.randint(1,16,size=(5,3))
print(arr)

[[14 11  2]
 [10 11 15]
 [11  2  2]
 [10  3 10]
 [ 7  8  9]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [53]:
arr = np.random.randint(1,17,size=(2,2,4))
print(arr)

[[[ 6  2  2  4]
  [ 9  2  4  6]]

 [[ 8  1  1 13]
  [ 4  8 12  1]]]


33. Swap axes of the array you created in Question 32

In [54]:
arr = arr.reshape(4,2,2)
print(arr)

[[[ 6  2]
  [ 2  4]]

 [[ 9  2]
  [ 4  6]]

 [[ 8  1]
  [ 1 13]]

 [[ 4  8]
  [12  1]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [56]:
arr = np.random.rand(10)
arr[np.sqrt(arr) < 0.5] = 0
print(arr)

[0.64286681 0.00534005 0.79518935 0.36362632 0.60407708 0.92760421
 0.60092776 0.10455738 0.97128311 0.72282554]
[0.64286681 0.         0.79518935 0.36362632 0.60407708 0.92760421
 0.60092776 0.         0.97128311 0.72282554]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [58]:
arr1 = np.random.rand(12)
arr2 = np.random.rand(12)
arr3 = np.maximum(arr1,arr2)
print(arr3)

[0.95046009 0.866403   0.5823001  0.74507739 0.39362927 0.39641594
 0.41702751 0.85866125 0.61602662 0.88397982 0.88263409 0.66053273]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [60]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names = np.unique(names)
names = np.sort(names)
print(names)

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [66]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
a = np.setdiff1d(a,b)
print(a)

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [76]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])

newColumn = np.array([[10,10,10]])
sampleArray[:,1]= newColumn
print(sampleArray)

[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [77]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
z = np.dot(x,y)
print(z)

[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum